### PR TITLE
Fix BLKSSZGET and BLKPBSZGET for mips and powerpc

### PR DESCRIPTION
**Pull request by Mek101**
Found out a couple of things while contributing to https://github.com/rust-lang/libc/pull/2548 thanks to the tests

### CODE REVIEW

**Comment by Mek101** [comment]
Even though I ran `cd gen/ && cargo run --release` and then added `src/`?

**Comment by sunfishcode** [comment]
The key difference seems to be:
```diff
diff --git a/src/v5_4/x86_64/netlink.rs b/src/v5_4/x86_64/netlink.rs
index e6b87db..a31fb4f 100644
--- a/src/v5_4/x86_64/netlink.rs
+++ b/src/v5_4/x86_64/netlink.rs
@@ -1,4 +1,4 @@
-/* automatically generated by rust-bindgen 0.59.1 */
+/* automatically generated by rust-bindgen 0.59.2 */
 ```
Can you run `cargo update` and then retry the `cd gen/ && cargo run --release`? And then also add `cargo update && ` to the front of that command in the README.md too :-).

**Comment by sunfishcode** [comment]
I'm sure sure what's happening here; this is still seeing diffs like
```
-/* automatically generated by rust-bindgen 0.59.1 */
+/* automatically generated by rust-bindgen 0.59.2 */
```

**Comment by Mek101** [comment]
I don't think I can do anything to fix it: it is caused by a dependency being updated. Either you also update the check or ignore it, because it doesn't look like it will ever pass

**Comment by Mek101** [comment]
WTH
I pinned it to 0.59.1, why is it using 0.59.2?

**Comment by sunfishcode** [comment]
To pin a specific version, prepend "=" to it. [docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#comparison-requirements)

**Comment by Mek101** [comment]
It is ` bindgen = { version = "0.59.1", default-features = false, features = ["which-rustfmt"] }`

**Comment by sunfishcode** [comment]
Prepend "=" to the version string, like this:

`bindgen = { version = "=0.59.1", default-features = false, features = ["which-rustfmt"] }`

**Comment by bjorn3** [comment]
You need `version = "=0.59.1"` instead of `version = "0.59.1"`. Without the `=` cargo is allowed to pick any version semver compatible with `0.59.1`. That is version 0.59.z for any z >= 1.

**Comment by Mek101** [comment]
Yay!

**Comment by Mek101** [comment]
You may want to squash the last two commits after merging (or should I do it?)

**Comment by sunfishcode** [comment]
It's more convenient for me if you squash them, since the github squash UI just lets you squash everything or nothing. Thanks!

**Comment by Mek101** [comment]
Done

**Comment by sunfishcode** [comment]
Thanks!

**Comment by sunfishcode** [comment]
This is now released in 0.0.37.

**Comment by Mek101** [comment]
❤️

**Pull request merged**
