### PR TITLE
Update to Linux 6.2

### PR DESCRIPTION
**Pull request by jordanisaacs**
Just an update of the headers to kernel v6.2.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Thanks!

**Comment by decathorpe** [comment]
Just out of curiosity, what is the motivation behind updating to latest and greatest kernel headers (which might or might not expose APIs available on older kernels - see the removal of constants related to the Speck cipher in this PR), if the MSRV is super conservative with "what's on debian stable" (which presumably also has ancient kernels)?

**Comment by sunfishcode** [comment]
I guess the motivation for updating to the latest headers is probably the new `IORING_*` constants.

Also, it's common to use new Linux features in programs that need to also run on old Linux versions, by handling `ENOSYS` and similar errors with a fallback path.

`FS_ENCRYPTION_MODE_SPECK128_256_XTS` and `FS_ENCRYPTION_MODE_SPECK128_256_CTS` were removed from upstream Linux [here](https://lore.kernel.org/lkml/20180806230437.21431-1-Jason@zx2c4.com/) because they were "unused, undesired, and have never actually been used by anybody". I did a semver bump, though it's unlikely anything would have broken.

If there are any features removed in any version that Rust programs are actually using or want to use, I'm open to discussing options for continuing to support them. Linux-raw-sys could bundle copies of the old declarations if needed.

**Comment by jordanisaacs** [comment]
Yep, I was updating the headers for the `IORING_*` constants.

**Pull request merged**
