### PR TITLE
Add `BLKSSZGET` and `BLKPBSZGET` `ioctl` arguments

### PR DESCRIPTION
**Pull request by Mek101**
Mostly solves #7. I was able to confirm that the `BLKSSZGET` and `BLKPBSZGET` macros resolve to the same values for every architecture but sparc, which is giving me odd results like 536875643 for `BLKSSZGET`.

### CODE REVIEW

**Comment by Mek101** [comment]
I don't understand why it fails: `git diff --exit-code` returns `1` if the the new generated bindings and what I suppose are the older ones are different, which they should be, since I've added 2 new fields as suggested in #7?

**Comment by Mek101** [comment]
I don't understand why it fails: `git diff --exit-code` returns `1` if the the new generated bindings and what I suppose are the older ones are different, which they should be, since I've added 2 new fields as suggested in #7?

**Comment by sunfishcode** [comment]
The repo includes a checked-in copy of the bindings, to make this crate easier to use by downstream users. The check here is confirming that the checked-in bindings match what would be generated. To update the generated bindings, you can run `cd gen && cargo run --release`, `git commit` the changes it makes, and then add that to the PR.

**Comment by Mek101** [comment]
Thank you!

**Comment by Mek101** [comment]
Added the sparc values with the last commit.

I obtained every value by ripping the relative defines from the respective `/arch/<arch>/include/uapi/asm/ioctl.h` headers and using them to calculate and print the values.

**Pull request merged**
